import {
  ArrowLeft,
  FileText,
  Download,
  Copy,
  Check,
  Cloud,
  Package,
  Sparkles,
  Zap,
  CheckCircle,
  AlertTriangle,
  TrendingUp,
  ArrowRight,
  Clock,
  Calendar,
  ChevronDown,
  ChevronUp,
  Briefcase,
  Target,
  GanttChartSquare,
  FlaskConical,
  X,
  Database,
  HardDrive,
  Info,
} from 'lucide-react';
import { useState, useMemo } from 'react';
import type { GeneratedPlan, PlanPhase, PlannedCapability, OpportunityAssessment, GenerationTrace } from '../types';
import { SalesforceExport } from './SalesforceExport';
import { generateServiceRecommendations, buildRecommendationContext } from '../utils/serviceRecommendations';

interface PlanPageProps {
  plan: GeneratedPlan;
  assessment?: OpportunityAssessment | null;
  onClose: () => void;
}

type Tab = 'plan' | 'timeline' | 'services';

export function PlanPage({ plan, assessment, onClose }: PlanPageProps) {
  const [activeTab, setActiveTab] = useState<Tab>('plan');
  const [copied, setCopied] = useState(false);
  const [expandedPhases, setExpandedPhases] = useState<number[]>([1]);
  const [deselectedServiceIds, setDeselectedServiceIds] = useState<Set<string>>(new Set());
  const [showTrace, setShowTrace] = useState(false);

  const hasAIContent = !!plan.aiGenerated?.markdown;

  const serviceRecommendations = useMemo(() => {
    if (!assessment) return [];
    const assessedLevels = new Map(Object.entries(assessment.trackAssessments || {}));
    if (assessedLevels.size < 1) return [];
    const context = buildRecommendationContext(
      assessedLevels,
      assessment.disciplines || ['messaging-personalization'],
      (assessment.industry as any) || undefined,
      assessment.marketingFoundation || undefined
    );
    return generateServiceRecommendations(context);
  }, [assessment]);

  const selectedServices = serviceRecommendations.filter(r => !deselectedServiceIds.has(r.service.id));
  const totalMin = selectedServices.reduce((s, r) => s + r.estimatedCost.min, 0);
  const totalMax = selectedServices.reduce((s, r) => s + r.estimatedCost.max, 0);

  const toggleServiceSelection = (id: string) => {
    setDeselectedServiceIds(prev => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const buildFullExport = () => {
    const base = plan.aiGenerated?.markdown || buildExportMarkdown(plan);
    if (selectedServices.length === 0) return base;
    const serviceLines = [
      '',
      '---',
      '',
      '## Services & Investment',
      '',
      `**Total Estimated Investment:** $${(totalMin / 1000).toFixed(0)}K – $${(totalMax / 1000).toFixed(0)}K`,
      '',
      ...selectedServices.map(r =>
        `### ${r.service.name} (${r.priority} priority)\n${r.rationale}\n**Est.:** $${(r.estimatedCost.min / 1000).toFixed(0)}K – $${(r.estimatedCost.max / 1000).toFixed(0)}K`
      ),
      '',
      '---',
      '*Generated by Merkle Salesforce Capability Planner*',
    ];
    return base + serviceLines.join('\n');
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(buildFullExport());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const content = buildFullExport();
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${plan.executiveSummary.clientName.replace(/\s+/g, '-')}-plan.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const togglePhase = (n: number) =>
    setExpandedPhases((prev) => (prev.includes(n) ? prev.filter((p) => p !== n) : [...prev, n]));

  const tabs: { id: Tab; label: string; icon: React.ReactNode; badge?: string }[] = [
    {
      id: 'plan',
      label: 'Roadmap',
      icon: <FileText className="w-4 h-4" />,
      badge: hasAIContent ? 'AI' : undefined,
    },
    {
      id: 'timeline',
      label: 'Timeline',
      icon: <GanttChartSquare className="w-4 h-4" />,
    },
    {
      id: 'services',
      label: 'Services & Export',
      icon: <Package className="w-4 h-4" />,
      badge: serviceRecommendations.length > 0 ? `${selectedServices.length}/${serviceRecommendations.length}` : undefined,
    },
  ];

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col">
      {/* Page header */}
      <div className="bg-gradient-to-r from-merkle-blue to-salesforce-blue flex-shrink-0">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          {/* Top bar */}
          <div className="flex items-center justify-between py-4">
            <button
              onClick={onClose}
              className="flex items-center gap-2 text-white/80 hover:text-white transition-colors text-sm font-medium"
            >
              <ArrowLeft className="w-4 h-4" />
              Back to Assessment
            </button>
            <div className="flex items-center gap-2">
              <button
                onClick={handleCopy}
                className="flex items-center gap-2 px-3 py-1.5 bg-white/15 hover:bg-white/25 text-white rounded-lg transition-colors text-sm"
              >
                {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                {copied ? 'Copied!' : 'Copy'}
              </button>
              <button
                onClick={handleDownload}
                className="flex items-center gap-2 px-3 py-1.5 bg-white/15 hover:bg-white/25 text-white rounded-lg transition-colors text-sm"
              >
                <Download className="w-4 h-4" />
                Download
              </button>
              {plan.generationTrace && (
                <button
                  onClick={() => setShowTrace(true)}
                  title="View generation trace"
                  className="flex items-center gap-1.5 px-2.5 py-1.5 bg-white/10 hover:bg-white/20 text-white/70 hover:text-white rounded-lg transition-colors text-sm"
                >
                  <FlaskConical className="w-4 h-4" />
                </button>
              )}
            </div>
          </div>

          {/* Title */}
          <div className="pb-4">
            <h1 className="text-2xl font-bold text-white">{plan.executiveSummary.clientName}</h1>
            <p className="text-white/70 text-sm mt-0.5">
              {plan.executiveSummary.opportunityName
                ? `${plan.executiveSummary.opportunityName} · `
                : ''}
              Recommendation Plan · {plan.generatedAt.toLocaleDateString()}
            </p>
          </div>

          {/* Tabs */}
          <div className="flex gap-1 -mb-px">
            {tabs.map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`flex items-center gap-2 px-4 py-2.5 text-sm font-medium rounded-t-lg transition-colors whitespace-nowrap ${
                  activeTab === tab.id
                    ? 'bg-white text-merkle-blue'
                    : 'text-white/75 hover:text-white hover:bg-white/10'
                }`}
              >
                {tab.icon}
                {tab.label}
                {tab.badge && (
                  <span
                    className={`text-xs px-1.5 py-0.5 rounded-full font-semibold ${
                      activeTab === tab.id
                        ? 'bg-merkle-blue text-white'
                        : 'bg-white/20 text-white'
                    }`}
                  >
                    {tab.badge}
                  </span>
                )}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Content area */}
      <div className="flex-1 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">

          {/* ── PLAN TAB ── */}
          {activeTab === 'plan' && (
            <div className="max-w-4xl mx-auto">
              {hasAIContent ? (
                /* AI-generated plan — this IS the plan */
                <div>
                  <div className="flex items-center gap-2 mb-6 text-sm text-violet-600">
                    <Sparkles className="w-4 h-4" />
                    <span>AI-generated with Claude · {plan.aiGenerated!.tokenUsage?.output.toLocaleString()} tokens</span>
                  </div>
                  <div className="prose prose-slate max-w-none bg-white rounded-xl border border-gray-200 p-8 shadow-sm">
                    <MarkdownRenderer content={plan.aiGenerated!.markdown} />
                  </div>
                </div>
              ) : (
                /* Template plan — single-scroll layout */
                <TemplatePlan
                  plan={plan}
                  expandedPhases={expandedPhases}
                  onTogglePhase={togglePhase}
                />
              )}
            </div>
          )}

          {/* ── TIMELINE TAB ── */}
          {activeTab === 'timeline' && (
            <TimelineTab plan={plan} />
          )}

          {/* ── SERVICES & EXPORT TAB ── */}
          {activeTab === 'services' && (
            <div className="max-w-4xl mx-auto space-y-6">
              {serviceRecommendations.length > 0 ? (
                <>
                  {/* Investment summary */}
                  <div className="bg-gradient-to-br from-merkle-blue/5 to-salesforce-blue/5 rounded-xl border border-merkle-blue/20 p-6 flex items-center justify-between">
                    <div>
                      <h2 className="font-bold text-gray-900 text-lg">Total Investment Range</h2>
                      <p className="text-sm text-gray-500 mt-0.5">
                        {selectedServices.length} of {serviceRecommendations.length} services selected · deselect to exclude from export
                      </p>
                    </div>
                    <div className="text-right">
                      <div className="text-3xl font-bold text-merkle-blue">
                        ${(totalMin / 1000).toFixed(0)}K – ${(totalMax / 1000).toFixed(0)}K
                      </div>
                      <div className="text-xs text-gray-500 mt-1">estimated engagement range</div>
                    </div>
                  </div>

                  {/* Service cards */}
                  <div className="space-y-4">
                    {serviceRecommendations.map((rec) => {
                      const isDeselected = deselectedServiceIds.has(rec.service.id);
                      const priorityConfig: Record<string, { bar: string; badge: string; label: string }> = {
                        critical: { bar: 'bg-red-500', badge: 'bg-red-50 border-red-200 text-red-700', label: 'Critical' },
                        high: { bar: 'bg-orange-500', badge: 'bg-orange-50 border-orange-200 text-orange-700', label: 'High' },
                        medium: { bar: 'bg-yellow-400', badge: 'bg-yellow-50 border-yellow-200 text-yellow-700', label: 'Medium' },
                        low: { bar: 'bg-blue-400', badge: 'bg-blue-50 border-blue-200 text-blue-700', label: 'Low' },
                      };
                      const p = priorityConfig[rec.priority] || priorityConfig.low;
                      return (
                        <div key={rec.service.id} className={`bg-white rounded-xl border overflow-hidden shadow-sm transition-opacity ${isDeselected ? 'opacity-40 border-gray-100' : 'border-gray-200'}`}>
                          <div className={`h-1 w-full ${isDeselected ? 'bg-gray-200' : p.bar}`} />
                          <div className="p-5">
                            <div className="flex items-start justify-between gap-4">
                              <div className="flex-1">
                                <div className="flex items-center gap-2 mb-2">
                                  <h3 className="font-semibold text-gray-900 text-base">{rec.service.name}</h3>
                                  {!isDeselected && (
                                    <span className={`text-xs px-2 py-0.5 rounded-full border font-medium ${p.badge}`}>
                                      {p.label} Priority
                                    </span>
                                  )}
                                  {isDeselected && (
                                    <span className="text-xs px-2 py-0.5 rounded-full bg-gray-100 text-gray-400 font-medium">
                                      Excluded
                                    </span>
                                  )}
                                </div>
                                <p className="text-sm text-gray-600 leading-relaxed">{rec.rationale}</p>
                                {rec.dependencies?.length > 0 && (
                                  <p className="text-xs text-gray-400 mt-2">
                                    Depends on: {rec.dependencies.join(', ')}
                                  </p>
                                )}
                              </div>
                              <div className="flex flex-col items-end gap-2 flex-shrink-0 pl-4 border-l border-gray-100">
                                {!isDeselected && (
                                  <div className="text-right">
                                    <div className="text-xs text-gray-400 mb-1">Estimated</div>
                                    <div className="font-bold text-merkle-blue text-lg">
                                      ${(rec.estimatedCost.min / 1000).toFixed(0)}K – ${(rec.estimatedCost.max / 1000).toFixed(0)}K
                                    </div>
                                    <div className="text-xs text-gray-500 capitalize mt-0.5">{rec.recommendedSize} engagement</div>
                                  </div>
                                )}
                                <button
                                  onClick={() => toggleServiceSelection(rec.service.id)}
                                  className={`text-xs px-3 py-1 rounded-full border font-medium transition-colors ${
                                    isDeselected
                                      ? 'border-merkle-blue text-merkle-blue hover:bg-merkle-blue/5'
                                      : 'border-gray-200 text-gray-500 hover:border-red-200 hover:text-red-500'
                                  }`}
                                >
                                  {isDeselected ? 'Re-include' : 'Exclude'}
                                </button>
                              </div>
                            </div>
                          </div>
                        </div>
                      );
                    })}
                  </div>

                  <p className="text-xs text-gray-400 text-center">
                    Investment ranges are indicative. Final scoping depends on client environment and requirements.
                    Excluded services won't appear in exports.
                  </p>
                </>
              ) : (
                <div className="text-center py-16 text-gray-400">
                  <Package className="w-12 h-12 mx-auto mb-3 opacity-40" />
                  <p>Complete more of the assessment to see tailored service recommendations.</p>
                </div>
              )}

              {/* ── Export section ── */}
              <hr className="border-gray-200" />

              {/* Download */}
              <div className="bg-white rounded-xl border border-gray-200 p-6 shadow-sm">
                <h2 className="font-bold text-gray-900 text-lg mb-1 flex items-center gap-2">
                  <Download className="w-5 h-5 text-gray-500" />
                  Download Plan
                </h2>
                <p className="text-sm text-gray-500 mb-4">
                  Export this plan as a Markdown document{selectedServices.length > 0 ? ' including selected services' : ''}.
                </p>
                <div className="flex gap-3">
                  <button
                    onClick={handleDownload}
                    className="flex items-center gap-2 px-4 py-2 bg-merkle-blue text-white rounded-lg hover:bg-merkle-blue/90 transition-colors font-medium text-sm"
                  >
                    <Download className="w-4 h-4" />
                    Download as Markdown
                  </button>
                  <button
                    onClick={handleCopy}
                    className="flex items-center gap-2 px-4 py-2 border border-gray-200 text-gray-700 rounded-lg hover:border-gray-300 transition-colors text-sm"
                  >
                    {copied ? <Check className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4" />}
                    {copied ? 'Copied!' : 'Copy to Clipboard'}
                  </button>
                </div>
              </div>

              {/* Salesforce */}
              <div className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
                <div className="px-6 pt-6 pb-2">
                  <h2 className="font-bold text-gray-900 text-lg mb-1 flex items-center gap-2">
                    <Cloud className="w-5 h-5 text-salesforce-blue" />
                    Export to Salesforce
                  </h2>
                  <p className="text-sm text-gray-500 mb-4">
                    Push this plan to Salesforce as opportunities based on{selectedServices.length > 0 ? ` ${selectedServices.length} selected services` : ' plan phases'}.
                  </p>
                </div>
                <SalesforceExport plan={plan} assessment={assessment} selectedServices={selectedServices} />
              </div>

              {/* How we built this — collapsed */}
              {plan.aiGenerated && (
                <details className="bg-gray-50 rounded-xl border border-gray-200 p-5">
                  <summary className="text-sm font-medium text-gray-700 cursor-pointer select-none flex items-center gap-2">
                    <Sparkles className="w-4 h-4 text-violet-400" />
                    How this plan was built
                  </summary>
                  <div className="mt-4 space-y-2 text-sm">
                    <div className="flex justify-between text-gray-600">
                      <span>Model</span>
                      <span className="font-medium text-gray-900">
                        {plan.aiGenerated.generatedWith === 'claude-sonnet' ? 'Claude Sonnet' : 'Claude Opus'}
                      </span>
                    </div>
                    {plan.aiGenerated.tokenUsage && (
                      <>
                        <div className="flex justify-between text-gray-600">
                          <span>Context sent</span>
                          <span className="font-medium text-gray-900">{plan.aiGenerated.tokenUsage.input.toLocaleString()} tokens</span>
                        </div>
                        <div className="flex justify-between text-gray-600">
                          <span>Plan generated</span>
                          <span className="font-medium text-gray-900">{plan.aiGenerated.tokenUsage.output.toLocaleString()} tokens</span>
                        </div>
                      </>
                    )}
                    <div className="flex justify-between text-gray-600">
                      <span>Reference data</span>
                      <span className="font-medium text-gray-900">ROI benchmarks, offering toolkits, journey frameworks</span>
                    </div>
                    {assessment?.disciplines && (
                      <div className="flex justify-between text-gray-600">
                        <span>Disciplines</span>
                        <span className="font-medium text-gray-900 capitalize">
                          {assessment.disciplines.map((d) => d.replace(/-/g, ' ')).join(', ')}
                        </span>
                      </div>
                    )}
                    {assessment?.industry && (
                      <div className="flex justify-between text-gray-600">
                        <span>Industry vertical</span>
                        <span className="font-medium text-gray-900 capitalize">{assessment.industry.replace(/-/g, ' ')}</span>
                      </div>
                    )}
                  </div>
                </details>
              )}
            </div>
          )}

        </div>
      </div>

      {/* Generation Trace Drawer */}
      {showTrace && plan.generationTrace && (
        <GenerationTraceDrawer
          trace={plan.generationTrace}
          onClose={() => setShowTrace(false)}
        />
      )}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Timeline / Gantt view
// ─────────────────────────────────────────────────────────────────────────────

function parseDurationMonths(duration: string): number {
  const range = duration.match(/(\d+)\s*[-–]\s*(\d+)\s*months?/i);
  if (range) return Math.round((parseInt(range[1]) + parseInt(range[2])) / 2);
  const months = duration.match(/(\d+)\s*months?/i);
  if (months) return parseInt(months[1]);
  const weeks = duration.match(/(\d+)\s*weeks?/i);
  if (weeks) return Math.max(1, Math.round(parseInt(weeks[1]) / 4));
  return 3;
}

interface ParsedPhase {
  phaseNumber: number;
  name: string;
  duration: string;
  capabilities: string[];
  milestones: string[];
}

/** Extract phases from AI-generated markdown so Timeline always matches the Roadmap. */
function parsePhasesFromMarkdown(markdown: string): ParsedPhase[] | null {
  // Match headers like: ## Phase 1: Name (Duration) or ### Phase 2 – Name
  const phaseRegex = /^#{2,4}\s+Phase\s+(\d+)[:\s–\-]+([^\n(]+?)(?:\s*\(([^)]+)\))?[ \t]*$/gm;
  const matches = [...markdown.matchAll(phaseRegex)];
  if (matches.length === 0) return null;

  return matches.map((match, i) => {
    const start = match.index!;
    const end = matches[i + 1]?.index ?? markdown.length;
    const section = markdown.slice(start, end);

    const phaseNumber = parseInt(match[1]);
    const name = match[2].trim().replace(/\s*[-–:]+\s*$/, '');
    const inlineDuration = match[3]?.trim();

    // Try to find duration elsewhere in the section
    const durationLine = section.match(/\*{0,2}Duration[:\s*]+\*{0,2}([^\n]+)/i)
                      || section.match(/(\d+[-–]\d+\s*months?|\d+\s*months?)/i);
    const duration = inlineDuration
      || durationLine?.[1]?.replace(/\*+/g, '').trim()
      || '3 months';

    // Bullet points → capabilities
    const bullets = [...section.matchAll(/^[ \t]*[-•*]\s+(.+)$/gm)].map(m => m[1].trim());

    // Named milestones subsection
    const msSection = section.match(/(?:Key\s+)?Milestones?[\s:]+\n((?:[ \t]*[-•*]\s+.+\n?)+)/i);
    const milestones = msSection
      ? [...msSection[1].matchAll(/^[ \t]*[-•*]\s+(.+)$/gm)].map(m => m[1].trim()).slice(0, 4)
      : [];

    return { phaseNumber, name, duration, capabilities: bullets.slice(0, 10), milestones };
  });
}

const PHASE_COLORS = [
  { bar: 'bg-blue-500',    light: 'bg-blue-50',    border: 'border-blue-200',    text: 'text-blue-700',    dot: 'bg-blue-500'    },
  { bar: 'bg-orange-500',  light: 'bg-orange-50',  border: 'border-orange-200',  text: 'text-orange-700',  dot: 'bg-orange-500'  },
  { bar: 'bg-emerald-500', light: 'bg-emerald-50', border: 'border-emerald-200', text: 'text-emerald-700', dot: 'bg-emerald-500' },
  { bar: 'bg-purple-500',  light: 'bg-purple-50',  border: 'border-purple-200',  text: 'text-purple-700',  dot: 'bg-purple-500'  },
];

/** Render inline markdown bold (**text**) as <strong> elements. */
function InlineText({ text }: { text: string }) {
  const parts = text.split(/\*\*(.+?)\*\*/g);
  return (
    <>
      {parts.map((part, i) =>
        i % 2 === 1
          ? <strong key={i} className="font-semibold text-gray-900">{part}</strong>
          : <span key={i}>{part}</span>
      )}
    </>
  );
}

function TimelineTab({ plan }: { plan: GeneratedPlan }) {
  const [expandedPhases, setExpandedPhases] = useState<Set<number>>(new Set());

  const phases: ParsedPhase[] = useMemo(() => {
    if (plan.aiGenerated?.markdown) {
      const parsed = parsePhasesFromMarkdown(plan.aiGenerated.markdown);
      if (parsed && parsed.length > 0) return parsed;
    }
    return plan.phases.map((p) => ({
      phaseNumber: p.phaseNumber,
      name: p.name,
      duration: p.duration,
      capabilities: p.capabilities.map((c) => c.capabilityName),
      milestones: p.keyMilestones,
    }));
  }, [plan]);

  const toggleExpanded = (n: number) =>
    setExpandedPhases((prev) => {
      const next = new Set(prev);
      next.has(n) ? next.delete(n) : next.add(n);
      return next;
    });

  if (phases.length === 0) {
    return (
      <div className="max-w-4xl mx-auto text-center py-20 text-gray-400">
        <GanttChartSquare className="w-12 h-12 mx-auto mb-3 opacity-30" />
        <p className="font-medium text-gray-500 mb-1">No structured timeline available</p>
        <p className="text-sm">This plan was generated as a narrative document. View the Roadmap tab for the full plan.</p>
      </div>
    );
  }

  const durations = phases.map((p) => parseDurationMonths(p.duration));
  const totalMonths = durations.reduce((s, d) => s + d, 0);

  let cursor = 0;
  const phaseLayout = phases.map((phase, i) => {
    const start = cursor;
    const dur = durations[i];
    cursor += dur;
    return { phase, start, dur, pct: (dur / totalMonths) * 100 };
  });

  const tickStep = totalMonths > 18 ? 2 : 1;
  const ticks = Array.from({ length: Math.ceil(totalMonths / tickStep) }, (_, i) => (i + 1) * tickStep).filter(t => t <= totalMonths);

  const CAP_LIMIT = 7;

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      {/* Legend */}
      <div className="flex items-center gap-6 flex-wrap">
        {phaseLayout.map(({ phase }, i) => {
          const c = PHASE_COLORS[i % PHASE_COLORS.length];
          return (
            <div key={phase.phaseNumber} className="flex items-center gap-2 text-sm">
              <div className={`w-3 h-3 rounded-sm ${c.bar}`} />
              <span className="text-gray-600 font-medium">Phase {phase.phaseNumber}: {phase.name}</span>
            </div>
          );
        })}
      </div>

      {/* Scrollable Gantt area */}
      <div className="overflow-x-auto pb-2">
        <div className="min-w-[560px]">
          {/* Month ruler */}
          <div className="relative w-full h-6 mb-2">
            {ticks.map((tick) => (
              <div
                key={tick}
                className="absolute top-0 flex flex-col items-center"
                style={{ left: `${(tick / totalMonths) * 100}%`, transform: 'translateX(-50%)' }}
              >
                <span className="text-xs text-gray-400 whitespace-nowrap">M{tick}</span>
              </div>
            ))}
          </div>

          {/* Gridlines + phase bars */}
          <div className="relative">
            <div className="absolute inset-0 pointer-events-none">
              {ticks.map((tick) => (
                <div
                  key={tick}
                  className="absolute top-0 bottom-0 border-l border-gray-100"
                  style={{ left: `${(tick / totalMonths) * 100}%` }}
                />
              ))}
            </div>
            <div className="relative flex h-14 rounded-xl overflow-hidden shadow-sm">
              {phaseLayout.map(({ phase, pct }, i) => {
                const c = PHASE_COLORS[i % PHASE_COLORS.length];
                return (
                  <div
                    key={phase.phaseNumber}
                    style={{ width: `${pct}%` }}
                    className={`${c.bar} flex items-center px-3 gap-2 overflow-hidden ${i > 0 ? 'border-l-2 border-white/30' : ''}`}
                  >
                    <div className="w-6 h-6 rounded-full bg-white/25 flex items-center justify-center text-white text-xs font-bold flex-shrink-0">
                      {phase.phaseNumber}
                    </div>
                    <div className="text-white min-w-0">
                      <div className="font-semibold text-sm leading-tight truncate">{phase.name}</div>
                      <div className="text-white/70 text-xs">{phase.duration}</div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Phase detail cards — proportional widths, same scroll container as bars */}
          <div className="flex gap-3 mt-4 items-start">
            {phaseLayout.map(({ phase, pct }, i) => {
              const c = PHASE_COLORS[i % PHASE_COLORS.length];
              const isExpanded = expandedPhases.has(phase.phaseNumber);
              const visible = isExpanded ? phase.capabilities : phase.capabilities.slice(0, CAP_LIMIT);
              const overflow = phase.capabilities.length - CAP_LIMIT;

              return (
                <div
                  key={phase.phaseNumber}
                  style={{ width: `${pct}%`, flexShrink: 0 }}
                  className={`${c.light} border ${c.border} rounded-xl p-4`}
                >
                  <div className={`text-xs font-bold ${c.text} uppercase tracking-wide mb-1`}>
                    Phase {phase.phaseNumber}
                  </div>
                  <div className="font-semibold text-gray-900 text-sm mb-1 leading-tight">{phase.name}</div>
                  <div className="text-xs text-gray-500 mb-3">{phase.duration}</div>

                  {/* Capabilities */}
                  {phase.capabilities.length > 0 && (
                    <div className="space-y-1.5 mb-3">
                      {visible.map((cap, ci) => (
                        <div key={ci} className="flex items-start gap-1.5 text-xs text-gray-700">
                          <div className={`w-1.5 h-1.5 rounded-full ${c.dot} mt-1 flex-shrink-0`} />
                          <span className="leading-snug"><InlineText text={cap} /></span>
                        </div>
                      ))}
                      {overflow > 0 && (
                        <button
                          onClick={() => toggleExpanded(phase.phaseNumber)}
                          className={`text-xs ${c.text} font-medium pl-3 hover:underline`}
                        >
                          {isExpanded ? '↑ Show less' : `+${overflow} more`}
                        </button>
                      )}
                    </div>
                  )}

                  {/* Milestones */}
                  {phase.milestones.length > 0 && (
                    <div className={`border-t ${c.border} pt-2 space-y-1`}>
                      {phase.milestones.map((m, j) => (
                        <div key={j} className={`flex items-start gap-1.5 text-xs ${c.text}`}>
                          <span className="flex-shrink-0 text-[10px] mt-0.5">◆</span>
                          <span className="leading-snug"><InlineText text={m} /></span>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      </div>

      {/* Quick wins */}
      {plan.quickWins.length > 0 && (
        <div className="bg-emerald-50 border border-emerald-200 rounded-xl p-4">
          <div className="flex items-center gap-2 mb-3">
            <Zap className="w-4 h-4 text-emerald-600" />
            <span className="font-semibold text-emerald-800 text-sm">Quick Wins — Start Immediately</span>
          </div>
          <div className="flex flex-wrap gap-2">
            {plan.quickWins.map((win, i) => (
              <div key={i} className="bg-white border border-emerald-200 rounded-lg px-3 py-2 text-sm">
                <div className="font-medium text-gray-900">{win.capabilityName}</div>
                {win.impact && <div className="text-xs text-emerald-600 mt-0.5">{win.impact}</div>}
              </div>
            ))}
          </div>
        </div>
      )}

      <p className="text-xs text-gray-400 text-center pb-2">
        Timeline durations are estimates. Actual sequencing depends on client readiness and resource availability.
      </p>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Template plan (single-scroll, used when no AI content)
// ─────────────────────────────────────────────────────────────────────────────

function TemplatePlan({
  plan,
  expandedPhases,
  onTogglePhase,
}: {
  plan: GeneratedPlan;
  expandedPhases: number[];
  onTogglePhase: (n: number) => void;
}) {
  return (
    <div className="space-y-8">
      {/* Executive summary stats */}
      <div className="bg-gradient-to-br from-gray-50 to-white rounded-xl border border-gray-200 p-6">
        <h2 className="font-bold text-gray-900 text-lg mb-4 flex items-center gap-2">
          <Target className="w-5 h-5 text-merkle-blue" />
          Executive Summary
        </h2>
        <p className="text-gray-700 mb-4">{plan.executiveSummary.overallRecommendation}</p>
        <p className="text-sm text-gray-500">{plan.executiveSummary.strategicRationale}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-6">
          {[
            { value: plan.executiveSummary.totalCapabilities, label: 'Capabilities', color: 'text-merkle-blue' },
            { value: plan.executiveSummary.immediateCapabilities, label: 'Immediate', color: 'text-emerald-600' },
            { value: plan.executiveSummary.nearFutureCapabilities, label: 'Near-Future', color: 'text-amber-600' },
            { value: plan.executiveSummary.recommendedTimeframe, label: 'Timeframe', color: 'text-gray-900' },
          ].map((stat) => (
            <div key={stat.label} className="bg-white rounded-lg p-4 border border-gray-100 text-center">
              <div className={`text-2xl font-bold ${stat.color}`}>{stat.value}</div>
              <div className="text-xs text-gray-500 mt-1">{stat.label}</div>
            </div>
          ))}
        </div>
        {plan.executiveSummary.estimatedTotalInvestment && (
          <div className="mt-4 p-4 bg-merkle-blue/5 rounded-lg border border-merkle-blue/20 flex justify-between items-center">
            <span className="font-medium text-gray-900">Estimated Investment</span>
            <span className="text-xl font-bold text-merkle-blue">{plan.executiveSummary.estimatedTotalInvestment}</span>
          </div>
        )}
      </div>

      {/* Quick wins */}
      {plan.quickWins.length > 0 && (
        <div className="bg-emerald-50 rounded-xl border border-emerald-200 p-6">
          <h2 className="font-bold text-gray-900 text-lg mb-4 flex items-center gap-2">
            <Zap className="w-5 h-5 text-emerald-600" />
            Quick Wins
          </h2>
          <div className="space-y-3">
            {plan.quickWins.map((win, i) => (
              <div key={i} className="flex items-start gap-3 bg-white rounded-lg p-3 border border-emerald-100">
                <CheckCircle className="w-5 h-5 text-emerald-600 flex-shrink-0 mt-0.5" />
                <div>
                  <div className="font-medium text-gray-900">{win.capabilityName}</div>
                  <div className="text-sm text-gray-600">{win.description}</div>
                  <div className="text-sm text-emerald-600 font-medium mt-1">Impact: {win.impact}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Phases */}
      {plan.phases.length > 0 && (
        <div>
          <h2 className="font-bold text-gray-900 text-lg mb-4 flex items-center gap-2">
            <Calendar className="w-5 h-5 text-merkle-blue" />
            Implementation Phases
          </h2>
          <div className="space-y-4">
            {plan.phases.map((phase) => (
              <PhaseCard
                key={phase.phaseNumber}
                phase={phase}
                isExpanded={expandedPhases.includes(phase.phaseNumber)}
                onToggle={() => onTogglePhase(phase.phaseNumber)}
              />
            ))}
          </div>
        </div>
      )}

      {/* Commercial */}
      <div className="bg-white rounded-xl border border-gray-200 p-6">
        <h2 className="font-bold text-gray-900 text-lg mb-4 flex items-center gap-2">
          <Briefcase className="w-5 h-5 text-merkle-blue" />
          Engagement Model
        </h2>
        <div className="text-xl font-bold text-merkle-blue mb-2">{plan.commercialSummary.recommendedModel}</div>
        <p className="text-gray-600 mb-4">{plan.commercialSummary.modelRationale}</p>
        {plan.commercialSummary.phasedInvestment.length > 0 && (
          <div className="space-y-2">
            {plan.commercialSummary.phasedInvestment.map((inv, i) => (
              <div key={i} className="flex justify-between p-3 bg-gray-50 rounded-lg">
                <span className="text-gray-700">Phase {inv.phase}: {inv.description}</span>
                <span className="font-bold text-gray-900">{inv.estimateRange}</span>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Risks + Success metrics side by side */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {plan.risks.length > 0 && (
          <div className="bg-white rounded-xl border border-gray-200 p-6">
            <h2 className="font-bold text-gray-900 mb-4 flex items-center gap-2">
              <AlertTriangle className="w-5 h-5 text-amber-500" />
              Key Risks
            </h2>
            <div className="space-y-3">
              {plan.risks.slice(0, 4).map((risk, i) => (
                <div key={i} className="text-sm">
                  <div className="flex items-center justify-between">
                    <span className="font-medium text-gray-900">{risk.risk}</span>
                    <span className={`text-xs px-1.5 py-0.5 rounded ${risk.likelihood === 'high' ? 'bg-red-100 text-red-700' : 'bg-amber-100 text-amber-700'}`}>
                      {risk.likelihood}
                    </span>
                  </div>
                  <p className="text-gray-500 mt-1">{risk.mitigation}</p>
                </div>
              ))}
            </div>
          </div>
        )}
        {plan.successMetrics.length > 0 && (
          <div className="bg-white rounded-xl border border-gray-200 p-6">
            <h2 className="font-bold text-gray-900 mb-4 flex items-center gap-2">
              <TrendingUp className="w-5 h-5 text-emerald-500" />
              Success Metrics
            </h2>
            <div className="space-y-3">
              {plan.successMetrics.slice(0, 4).map((m, i) => (
                <div key={i} className="flex justify-between text-sm">
                  <span className="text-gray-700">{m.metric}</span>
                  <span className="font-medium text-emerald-600">{m.target}</span>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Next steps */}
      {plan.nextSteps.length > 0 && (
        <div className="bg-white rounded-xl border border-gray-200 p-6">
          <h2 className="font-bold text-gray-900 text-lg mb-4 flex items-center gap-2">
            <ArrowRight className="w-5 h-5 text-merkle-blue" />
            Next Steps
          </h2>
          <div className="space-y-3">
            {plan.nextSteps.map((step, i) => (
              <div key={i} className="flex items-start gap-3">
                <div className="w-6 h-6 rounded-full bg-merkle-blue/10 text-merkle-blue flex items-center justify-center text-sm font-bold flex-shrink-0 mt-0.5">
                  {i + 1}
                </div>
                <div className="flex-1">
                  <div className="font-medium text-gray-900">{step.step}</div>
                  <div className="flex items-center gap-3 mt-1 text-xs text-gray-500">
                    <span className={`px-2 py-0.5 rounded font-medium ${
                      step.owner === 'merkle' ? 'bg-merkle-blue/10 text-merkle-blue' :
                      step.owner === 'client' ? 'bg-gray-100 text-gray-600' :
                      'bg-purple-100 text-purple-600'
                    }`}>
                      {step.owner === 'joint' ? 'Joint' : step.owner === 'merkle' ? 'Merkle' : 'Client'}
                    </span>
                    <span className="flex items-center gap-1"><Clock className="w-3 h-3" />{step.timeline}</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Generation Trace Drawer
// ─────────────────────────────────────────────────────────────────────────────

function GenerationTraceDrawer({ trace, onClose }: { trace: GenerationTrace; onClose: () => void }) {
  const [expandedChunks, setExpandedChunks] = useState<Set<string>>(new Set());

  const toggleChunk = (id: string) => setExpandedChunks(prev => {
    const next = new Set(prev);
    if (next.has(id)) next.delete(id); else next.add(id);
    return next;
  });

  const totalChars = trace.referenceChunks.reduce((s, c) => s + c.charCount, 0);
  const dbChunks = trace.referenceChunks.filter(c => c.source === 'database');
  const hardcodedChunks = trace.referenceChunks.filter(c => c.source === 'hardcoded');

  const TRACK_LABELS: Record<string, string> = {
    'data-identity': 'Data & Identity',
    'journeys': 'Customer Journeys',
    'content-channels': 'Content & Channels',
    'intelligence': 'Intelligence',
  };

  return (
    <div className="fixed inset-0 z-50 flex justify-end">
      <div className="absolute inset-0 bg-black/30" onClick={onClose} />
      <div className="relative w-full max-w-xl bg-slate-900 text-slate-100 flex flex-col h-full shadow-2xl">
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-slate-700 flex-shrink-0">
          <div className="flex items-center gap-2.5">
            <FlaskConical className="w-5 h-5 text-violet-400" />
            <div>
              <h2 className="text-base font-semibold text-white">Generation Trace</h2>
              <p className="text-xs text-slate-400 mt-0.5">What went into creating this plan</p>
            </div>
          </div>
          <button onClick={onClose} className="text-slate-400 hover:text-slate-200 transition-colors">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto px-5 py-5 space-y-6">

          {/* Model & Generation */}
          <section>
            <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-3">Model & Generation</h3>
            <div className="bg-slate-800 rounded-lg p-4 space-y-2.5">
              <TraceRow label="Model" value={trace.model} mono />
              <TraceRow label="Mode" value={trace.quality === 'enhanced' ? 'Enhanced (2-pass)' : 'Standard (single-pass)'} />
              <TraceRow label="Cache Hit" value={
                <span className={`px-2 py-0.5 rounded text-xs font-medium ${trace.cacheHit ? 'bg-amber-900/50 text-amber-300' : 'bg-green-900/50 text-green-300'}`}>
                  {trace.cacheHit ? 'Yes — served from cache' : 'No — freshly generated'}
                </span>
              } />
              <TraceRow label="Ref Data" value={
                <span className={`inline-flex items-center gap-1.5 px-2 py-0.5 rounded text-xs font-medium ${
                  trace.referenceDataSource === 'database' ? 'bg-violet-900/50 text-violet-300' : 'bg-slate-700 text-slate-300'
                }`}>
                  {trace.referenceDataSource === 'database'
                    ? <><Database className="w-3 h-3" /> Database (live)</>
                    : <><HardDrive className="w-3 h-3" /> Hardcoded fallback</>}
                </span>
              } />
              <TraceRow label="System prompt" value={`${(trace.promptStats.systemPromptChars / 1000).toFixed(1)}K chars`} mono />
              <TraceRow label="User prompt" value={`${(trace.promptStats.userPromptChars / 1000).toFixed(1)}K chars`} mono />
              <TraceRow label="Input tokens" value={trace.promptStats.inputTokens.toLocaleString()} mono />
              <TraceRow label="Output tokens" value={trace.promptStats.outputTokens.toLocaleString()} mono />
            </div>
          </section>

          {/* Inputs Analyzed */}
          <section>
            <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-3">Inputs Analyzed</h3>
            <div className="bg-slate-800 rounded-lg p-4 space-y-2.5">
              <TraceRow label="Industry" value={trace.inputSummary.industry || '—'} />
              <TraceRow label="Foundation" value={trace.inputSummary.marketingFoundation || '—'} />
              <TraceRow label="Company Size" value={trace.inputSummary.companySize || '—'} />
              <TraceRow label="Budget" value={trace.inputSummary.budgetRange || '—'} />
              {trace.inputSummary.engagementModels.length > 0 && (
                <TraceRow label="Eng. Models" value={trace.inputSummary.engagementModels.join(', ')} />
              )}
              {trace.inputSummary.businessDrivers.length > 0 && (
                <TraceRow label="Business Drivers" value={
                  <ul className="space-y-0.5">
                    {trace.inputSummary.businessDrivers.map((d, i) => <li key={i} className="text-xs text-slate-300">{d}</li>)}
                  </ul>
                } />
              )}
            </div>
            {trace.inputSummary.tracksAssessed.length > 0 && (
              <div className="mt-2 bg-slate-800 rounded-lg overflow-hidden">
                <table className="w-full text-xs">
                  <thead>
                    <tr className="border-b border-slate-700">
                      <th className="text-left px-4 py-2 text-slate-400 font-medium">Track</th>
                      <th className="text-left px-4 py-2 text-slate-400 font-medium">Level</th>
                      <th className="text-left px-4 py-2 text-slate-400 font-medium">Status</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-700/50">
                    {trace.inputSummary.tracksAssessed.map((ta, i) => (
                      <tr key={i}>
                        <td className="px-4 py-2 text-slate-300">{TRACK_LABELS[ta.trackId] || ta.trackId}</td>
                        <td className="px-4 py-2 text-slate-300">{ta.level}</td>
                        <td className="px-4 py-2">
                          <span className={`px-1.5 py-0.5 rounded text-xs font-medium ${
                            ta.status === 'complete' ? 'bg-green-900/50 text-green-300' :
                            ta.status === 'in-progress' ? 'bg-amber-900/50 text-amber-300' :
                            'bg-slate-700 text-slate-400'
                          }`}>{ta.status}</span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </section>

          {/* Reference Data Chunks */}
          <section>
            <div className="flex items-center justify-between mb-3">
              <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Reference Data Injected</h3>
              <span className="text-xs text-slate-500">{trace.referenceChunks.length} chunks · {(totalChars / 1000).toFixed(1)}K chars</span>
            </div>
            <div className="space-y-1.5">
              {dbChunks.length > 0 && (
                <>
                  <div className="flex items-center gap-2 text-xs text-violet-400 font-medium py-1">
                    <Database className="w-3 h-3" /> Database chunks ({dbChunks.length})
                  </div>
                  {dbChunks.map(chunk => (
                    <ChunkCard key={chunk.id} chunk={chunk} expanded={expandedChunks.has(chunk.id)} onToggle={() => toggleChunk(chunk.id)} />
                  ))}
                </>
              )}
              {hardcodedChunks.length > 0 && (
                <>
                  <div className="flex items-center gap-2 text-xs text-slate-400 font-medium py-1 mt-2">
                    <HardDrive className="w-3 h-3" /> Hardcoded chunks ({hardcodedChunks.length})
                  </div>
                  {hardcodedChunks.map(chunk => (
                    <ChunkCard key={chunk.id} chunk={chunk} expanded={expandedChunks.has(chunk.id)} onToggle={() => toggleChunk(chunk.id)} />
                  ))}
                </>
              )}
            </div>
          </section>

          <div className="flex items-start gap-2 p-3 bg-slate-800/50 rounded-lg text-xs text-slate-500">
            <Info className="w-3.5 h-3.5 flex-shrink-0 mt-0.5" />
            <span>Previews show the first 500 chars of each chunk as injected into Claude's context window. Old plans generated before this feature was added will not have a trace.</span>
          </div>
        </div>
      </div>
    </div>
  );
}

function TraceRow({ label, value, mono }: { label: string; value: React.ReactNode; mono?: boolean }) {
  return (
    <div className="flex items-start gap-3">
      <span className="text-slate-500 w-28 flex-shrink-0 text-xs pt-0.5">{label}</span>
      <span className={`text-slate-200 flex-1 ${mono ? 'font-mono text-xs' : 'text-sm'}`}>{value}</span>
    </div>
  );
}

function ChunkCard({ chunk, expanded, onToggle }: {
  chunk: GenerationTrace['referenceChunks'][0];
  expanded: boolean;
  onToggle: () => void;
}) {
  return (
    <div className="bg-slate-800 rounded-lg overflow-hidden">
      <button
        onClick={onToggle}
        className="w-full flex items-center justify-between px-3 py-2.5 hover:bg-slate-700/50 transition-colors"
      >
        <div className="flex items-center gap-2 min-w-0">
          <span className={`w-2 h-2 rounded-full flex-shrink-0 ${chunk.source === 'database' ? 'bg-violet-400' : 'bg-slate-500'}`} />
          <span className="text-sm text-slate-200 truncate">{chunk.label}</span>
          <span className="text-xs text-slate-500 flex-shrink-0">{(chunk.charCount / 1000).toFixed(1)}K chars</span>
        </div>
        {expanded ? <ChevronUp className="w-3.5 h-3.5 text-slate-500 flex-shrink-0" /> : <ChevronDown className="w-3.5 h-3.5 text-slate-500 flex-shrink-0" />}
      </button>
      {expanded && (
        <div className="px-3 pb-3">
          <pre className="text-xs text-slate-400 whitespace-pre-wrap font-mono leading-relaxed bg-slate-900/50 rounded p-3 max-h-64 overflow-y-auto">
            {chunk.preview}{chunk.preview.length >= 500 ? '\n…[truncated]' : ''}
          </pre>
        </div>
      )}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Phase accordion card
// ─────────────────────────────────────────────────────────────────────────────

function PhaseCard({
  phase,
  isExpanded,
  onToggle,
}: {
  phase: PlanPhase;
  isExpanded: boolean;
  onToggle: () => void;
}) {
  const colors: Record<number, string> = {
    1: 'from-blue-500 to-blue-600',
    2: 'from-orange-500 to-orange-600',
    3: 'from-emerald-500 to-emerald-600',
    4: 'from-purple-500 to-purple-600',
  };

  return (
    <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
      <button
        onClick={onToggle}
        className="w-full px-6 py-4 flex items-center justify-between hover:bg-gray-50 transition-colors"
      >
        <div className="flex items-center gap-4">
          <div className={`w-10 h-10 rounded-lg bg-gradient-to-br ${colors[phase.phaseNumber] || colors[1]} flex items-center justify-center text-white font-bold`}>
            {phase.phaseNumber}
          </div>
          <div className="text-left">
            <div className="font-bold text-gray-900">{phase.name}</div>
            <div className="text-sm text-gray-500">{phase.capabilities.length} capabilities · {phase.duration}</div>
          </div>
        </div>
        <div className="flex items-center gap-3">
          {phase.totalEstimate && <span className="text-sm font-medium text-gray-600">{phase.totalEstimate}</span>}
          {isExpanded ? <ChevronUp className="w-5 h-5 text-gray-400" /> : <ChevronDown className="w-5 h-5 text-gray-400" />}
        </div>
      </button>

      {isExpanded && (
        <div className="px-6 pb-6 space-y-4">
          <p className="text-gray-600">{phase.description}</p>
          <div className="space-y-2">
            {phase.capabilities.map((cap) => (
              <CapabilityRow key={cap.capabilityId} capability={cap} />
            ))}
          </div>
          {phase.keyMilestones.length > 0 && (
            <div className="flex flex-wrap gap-2">
              {phase.keyMilestones.map((m, i) => (
                <span key={i} className="px-3 py-1 bg-gray-100 text-gray-700 rounded-full text-sm">{m}</span>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Capability row
// ─────────────────────────────────────────────────────────────────────────────

function CapabilityRow({ capability }: { capability: PlannedCapability }) {
  const [open, setOpen] = useState(false);

  const colors: Record<string, string> = {
    critical: 'bg-red-100 text-red-700',
    high: 'bg-orange-100 text-orange-700',
    medium: 'bg-blue-100 text-blue-700',
    'nice-to-have': 'bg-gray-100 text-gray-600',
  };

  return (
    <div className="bg-gray-50 rounded-lg overflow-hidden">
      <button
        onClick={() => setOpen(!open)}
        className="w-full p-4 flex items-center justify-between hover:bg-gray-100 transition-colors"
      >
        <div className="flex items-center gap-3">
          <CheckCircle className={`w-5 h-5 flex-shrink-0 ${capability.relevance === 'immediately-relevant' ? 'text-emerald-500' : 'text-amber-400'}`} />
          <span className="font-medium text-gray-900 text-sm">{capability.capabilityName}</span>
          <span className={`px-2 py-0.5 rounded text-xs font-medium ${colors[capability.priority] || colors['nice-to-have']}`}>
            {capability.priority}
          </span>
        </div>
        {open ? <ChevronUp className="w-4 h-4 text-gray-400" /> : <ChevronDown className="w-4 h-4 text-gray-400" />}
      </button>
      {open && (
        <div className="px-4 pb-4 space-y-2 text-sm">
          <p className="text-gray-600"><strong className="text-gray-700">Rationale:</strong> {capability.rationale}</p>
          {capability.clientInputSummary && (
            <p className="text-gray-600"><strong className="text-gray-700">Client context:</strong> {capability.clientInputSummary}</p>
          )}
          {capability.recommendedOfferings.length > 0 && (
            <div>
              <strong className="text-gray-700">Offerings:</strong>
              <div className="mt-1 space-y-1">
                {capability.recommendedOfferings.map((o, i) => (
                  <div key={i} className="flex justify-between bg-white rounded p-2 border border-gray-200">
                    <span className="text-gray-900">{o.offeringName} <span className="text-gray-400 text-xs">({o.offeringType})</span></span>
                    {o.estimateRange && <span className="text-merkle-blue font-medium">{o.estimateRange}</span>}
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Markdown renderer
// ─────────────────────────────────────────────────────────────────────────────

function MarkdownRenderer({ content }: { content: string }) {
  const html = useMemo(() => {
    let h = content
      .replace(/^### (.+)$/gm, '<h3 class="text-lg font-semibold text-gray-900 mt-6 mb-3">$1</h3>')
      .replace(/^## (.+)$/gm, '<h2 class="text-xl font-bold text-gray-900 mt-8 mb-4 pb-2 border-b border-gray-200">$1</h2>')
      .replace(/^# (.+)$/gm, '<h1 class="text-2xl font-bold text-gray-900 mt-8 mb-5">$1</h1>')
      .replace(/\*\*(.+?)\*\*/g, '<strong class="font-semibold text-gray-900">$1</strong>')
      .replace(/\*(.+?)\*/g, '<em>$1</em>')
      .replace(/^- (.+)$/gm, '<li class="ml-4 mb-1.5 text-gray-700">$1</li>')
      .replace(/^(\d+)\. (.+)$/gm, '<li class="ml-4 mb-1.5 text-gray-700"><span class="font-medium">$1.</span> $2</li>')
      .replace(/`([^`]+)`/g, '<code class="px-1.5 py-0.5 bg-gray-100 rounded text-sm font-mono text-gray-800">$1</code>')
      .replace(/^---$/gm, '<hr class="my-6 border-gray-200" />')
      .replace(/\n\n/g, '</p><p class="mb-4 text-gray-700 leading-relaxed">');

    if (!h.startsWith('<h') && !h.startsWith('<p')) {
      h = `<p class="mb-4 text-gray-700 leading-relaxed">${h}</p>`;
    }
    h = h.replace(/(<li[^>]*>.*?<\/li>\s*)+/g, (m) => `<ul class="list-disc list-inside space-y-1 mb-4">${m}</ul>`);
    return h;
  }, [content]);

  return <div className="markdown-content" dangerouslySetInnerHTML={{ __html: html }} />;
}

// ─────────────────────────────────────────────────────────────────────────────
// Export helper
// ─────────────────────────────────────────────────────────────────────────────

function buildExportMarkdown(plan: GeneratedPlan): string {
  const lines: string[] = [
    `# Recommendation Plan: ${plan.executiveSummary.clientName}`,
    `Generated: ${plan.generatedAt.toLocaleDateString()}`,
    '',
    '## Executive Summary',
    plan.executiveSummary.overallRecommendation,
    '',
    plan.executiveSummary.strategicRationale,
    '',
    '## Implementation Phases',
  ];
  plan.phases.forEach((p) => {
    lines.push(`### Phase ${p.phaseNumber}: ${p.name} (${p.duration})`);
    lines.push(p.description);
    p.capabilities.forEach((c) => lines.push(`- ${c.capabilityName} (${c.priority})`));
    lines.push('');
  });
  lines.push('## Engagement Model', `**${plan.commercialSummary.recommendedModel}**`, '', plan.commercialSummary.modelRationale, '');
  lines.push('## Next Steps');
  plan.nextSteps.forEach((s, i) => lines.push(`${i + 1}. ${s.step} (${s.owner}, ${s.timeline})`));
  lines.push('', '---', '*Generated by Merkle Salesforce Capability Planner*');
  return lines.join('\n');
}
